### ISSUE TITLE
TST: Handle test warnings

### ISSUE THREAD

**Issue by pllim** [astropy/specreduce#93]
At the time of posting, there are 4 warnings. These should be handled accordingly. You might want to turn all unhandled warnings into exceptions going forward in pytest settings to ensure no surprise warnings creep back in.

You can ignore this one: sunpy/ndcube#514
```
.../ndcube/version.py:27
  .../ndcube/version.py:27: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    for j, piece in enumerate(LooseVersion(version).version[:3]):
```

Is this good or bad? What is `specreduce_data`? Does it block release?
```
.../specreduce/calibration_data.py:34
  .../specreduce/calibration_data.py:34: AstropyUserWarning: Can't import specreduce_data package. Falling back to downloading data...
    warnings.warn(
```

This is not a blocker but assumption is dangerous. Should update the code so it does not generate this warning.
```
specreduce/tests/test_extinction.py::test_missing_extinction_unit
  .../specreduce/calibration_data.py:292: AstropyUserWarning: Input extinction is not a Quanitity. Assuming it is given in magnitudes...
    warnings.warn(
```

Is this warning expected? If so, use `pytest.warns` in the test. If not, fix the test case.
```
specreduce/tests/test_extinction.py::test_transmission_model
  .../astropy/units/function/logarithmic.py:46: RuntimeWarning: divide by zero encountered in log10
    return dex.to(self._function_unit, np.log10(x))
```

**Comment by tepickering** [comment]
the `specreduce_data` warnings are intentional to alert the user that data is being downloaded. the idea was to have users install `specreduce_data` to have all of the data cached locally and fall back to downloading the data if it's not installed. it may be that we'd rather just always download the data. i'll mark those warning as expected for now.

the extinction quantity assumption is a safe one. extinction is always given in magnitudes, transmission as a unitless fraction.

divide by zero is always gonna crop up when you're doing logarithms with data that can have values of <=0. numpy does the right thing under the hood of setting those to `-inf` or `nan` as appropriate so it's safe to expect the warning.

**Comment by pllim** [comment]
If these warnings are *expected*, please use `pytest.warns()`. If you want to *ignore* them altogether, please use `pytest.mark.filterwarnings()`. Also see https://docs.pytest.org/en/stable/how-to/capture-warnings.html

Thanks!

**Comment by tepickering** [comment]
i have folded these changes into #107
